### ISSUE TITLE
Updating an interaction

### ISSUE THREAD

**Issue by bevdokimov** [cybercussion/SCOBot#10]
Hi, 

first of all, thank you for providing the SCOBot open-source, it's really a big helper. 

I am using the SCOBot#setInteraction method to record question answers. I have a case in my project where I want to update only the timestamp(the time when the user starts working actively on the interaction). In [the wiki section](https://github.com/cybercussion/SCOBot/wiki/SCORM-SCOBot-Documentation#note-updating-an-interaction) it is stated that one could send only the items that have updated(another great feature).
Unfortunately, I get error messages stating that I have not set some items. I was assuming that the SCOBot would just write the timestamp in the existing interaction. Do I misunderstand what you have written in the wiki?

Thank you very much in advance for your time.

**Comment by cybercussion** [comment]
Closing this out.  Let me know if you have any further issues or debugging needs.
