### ISSUE TITLE
SCORM Player

### ISSUE THREAD

**Issue by thihara** [cybercussion/SCOBot#5]
Hi,

Is this a SCORM player capable of parsing the imsmanifest.xml file and serving the content with sequencing?

I went through most of the documentation but couldn't really find a way to parse a SCORM content package.

Thanks,
Thihara

**Comment by cybercussion** [comment]
Hi,
The content API isn't responsible for doing this.  The LMS level back end scripting normally performs this on content import.  It is possible at the LMS level to read it real time and render a table of contents.  But it is the LMS's job to provide the TOC and SCORM Runtime API.

**Comment by thihara** [comment]
Copy that. Thanks for clearing that up.
