### ISSUE TITLE
AICC Player

### ISSUE THREAD

**Issue by shyamprasadkr** [cybercussion/SCOBot#6]
Hi,
I'm trying to consume scorm / AICC complaint course from my web application. Are there any standard players that can do this?

**Comment by cybercussion** [comment]
AICC is a different beast.  It pre-dated XML so its all INI file style configurations in content.  This wasn't something that directly correlated to SCORM 1.2 or SCORM 2004 which as you can tell from the commit history in git took a while to sort out.

Digging up my old knowledge of AICC it actually performed its communication over something like the SCORM 1.2 "API" namespace but also supported HACP which contrary to SCORM would allow for cross-domain communication.  This effectively worked like a IFRAME communicating with a endpoint.  There is a "AICC_URL" query string value in this situation within the URL of the content.
This comes back more was plain text with line ending delimiters.

     * Parse AICC Response
     * AICC Responds in plain text with delimiters.
     * error=0
     * version=2
     * aicc_data=[core]
     * student_id=mark@cybercussion.com
     * student_name=Statkus, Mark
     * credit=credit
     * lesson_location=page1.html
     * lesson_mode=normal
     * lesson_status=i,resume
     * score=
     * time=0000:55:57
     * [core_lesson] *supports 4096
     * [core_vendor] *supports 4096 or point to a file
     * [objectives_status]
     * [student_data]
     * mastery_score=
     * max_time_allowed=0000:00:00
     * time_limit_action=continue,no message


SCOBot Content API did not make use of this this this required a bit of work to support both SCORM 1.2, 2004 which is a Javascript only API line of communication and then AICC which would require a AJAX request and a very different data model to support.  

If you are speaking at AICC at a server level than this project unfortunately does not cover Runtime API's used.  This is mainly a content API for developers to interface the LMS.

Hope that helps.
