### ISSUE TITLE
Can you use SCObot with scormpool player to emulate an LMS>

### ISSUE THREAD

**Issue by githarkirat** [cybercussion/SCOBot#8]
Hi,

I am a product owner at leapest.com, and we are evaluating SCObot. We are currently using the scormpool player to serve scorm packages without an LMS. Is it possible to use SCObot in conjunction with scormpool to get and set `cmi` object data across instances? Please let us know if you are available for detailed discussions?

Best regards,
Harry

**Comment by githarkirat** [comment]
Hi Mark,

Is it possible for us to have a call and discuss this implementation. 

Thanks,
Harry

**Comment by cybercussion** [comment]
You may email at mark@cybercussion.com.
